project:
  title: "Eurobarometer"
  type: website

website:
  title: ""
  description: ""
  navbar:
    right:
      - survey.qmd
      - music.qmd
      - economic.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

